"""
IANA Media Types Loader

Loads the media types ontology generated from the IANA registry.

Usage:
    loader = MediaTypeLoader()
    loader.load("data/iana-media-types/media-types.ttl")
    
    graph = loader.get_graph()
    
Note: You must first run download_iana.py to generate the data:
    python download_iana.py data/iana-media-types/
"""

from pathlib import Path
from typing import Set, List, Dict, Optional, Union
from dataclasses import dataclass, field
import logging

from rdflib import Graph, Namespace, URIRef, Literal
from rdflib.namespace import RDF, RDFS, OWL, SKOS

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# =============================================================================
# Namespaces (W3C Official)
# =============================================================================

# W3C official namespace for media type instances
W3C_MT = Namespace("https://www.w3.org/ns/iana/media-types/")

# Ontology namespace (for MediaType class, etc.)
MT_ONT = Namespace("https://www.w3.org/ns/iana/media-types/ontology#")


class MediaTypeNamespaces:
    """Media type namespace registry."""
    
    # W3C official namespace for media type resources
    # Example: https://www.w3.org/ns/iana/media-types/image/png#Resource
    W3C_MT = W3C_MT
    
    # Ontology classes namespace
    # Example: https://www.w3.org/ns/iana/media-types/ontology#MediaType
    MT_ONT = MT_ONT
    
    @classmethod
    def prefix_map(cls) -> Dict[str, Namespace]:
        return {
            "mt": cls.W3C_MT,
            "mt-ont": cls.MT_ONT,
        }
    
    @classmethod
    def get_uri_for_media_type(cls, media_type: str) -> URIRef:
        """
        Get the W3C URI for a media type string.
        
        Args:
            media_type: e.g., "image/png"
            
        Returns:
            URIRef like https://www.w3.org/ns/iana/media-types/image/png#Resource
        """
        return URIRef(f"https://www.w3.org/ns/iana/media-types/{media_type}#Resource")


# =============================================================================
# Statistics
# =============================================================================

@dataclass
class LoadStats:
    """Statistics about loaded ontology."""
    total_triples: int = 0
    media_type_count: int = 0
    top_level_types: int = 0
    subclass_edges: int = 0
    sources: List[str] = field(default_factory=list)


# =============================================================================
# Loader
# =============================================================================

class MediaTypeLoader:
    """
    Loader for IANA Media Types ontology.
    
    Uses W3C official namespace:
        https://www.w3.org/ns/iana/media-types/{type}/{subtype}#Resource
    """
    
    def __init__(self):
        self._graph = Graph()
        self._sources: List[str] = []
        self._bind_prefixes()
    
    def _bind_prefixes(self) -> None:
        """Bind common prefixes."""
        for prefix, ns in MediaTypeNamespaces.prefix_map().items():
            self._graph.bind(prefix, ns)
        self._graph.bind("rdfs", RDFS)
        self._graph.bind("owl", OWL)
        self._graph.bind("skos", SKOS)
    
    def load(self, path: Union[str, Path]) -> int:
        """
        Load a media types TTL file.
        
        Args:
            path: Path to the .ttl file (generated by download_iana.py)
            
        Returns:
            Number of triples loaded
        """
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(
                f"File not found: {path}\n"
                f"Run 'python download_iana.py' first to download IANA data."
            )
        
        before = len(self._graph)
        self._graph.parse(str(path), format="turtle")
        loaded = len(self._graph) - before
        
        self._sources.append(str(path))
        logger.info(f"Loaded {loaded} triples from {path.name}")
        
        return loaded
    
    def get_graph(self) -> Graph:
        """Get the loaded RDF graph."""
        return self._graph
    
    def get_stats(self) -> LoadStats:
        """Get loading statistics."""
        g = self._graph
        
        # Count media types (classes with skos:notation containing "/")
        media_type_count = 0
        for _, _, notation in g.triples((None, SKOS.notation, None)):
            if isinstance(notation, Literal) and "/" in str(notation):
                media_type_count += 1
        
        # Count top-level types (direct subclasses of MediaType)
        top_level = len(list(g.subjects(RDFS.subClassOf, MT_ONT.MediaType)))
        
        return LoadStats(
            total_triples=len(g),
            media_type_count=media_type_count,
            top_level_types=top_level,
            subclass_edges=len(list(g.triples((None, RDFS.subClassOf, None)))),
            sources=self._sources.copy(),
        )
    
    def get_media_type_uris(self) -> Set[URIRef]:
        """Get all media type URIs."""
        uris = set()
        for s, _, notation in self._graph.triples((None, SKOS.notation, None)):
            if isinstance(s, URIRef) and isinstance(notation, Literal):
                if "/" in str(notation):  # Has type/subtype format
                    uris.add(s)
        return uris
    
    def get_labels(self) -> Dict[URIRef, str]:
        """Get labels (media type strings) for all media types."""
        labels = {}
        for uri in self.get_media_type_uris():
            for _, _, label in self._graph.triples((uri, SKOS.notation, None)):
                if isinstance(label, Literal):
                    labels[uri] = str(label)
                    break
        return labels
    
    def get_media_type_by_string(self, media_type: str) -> Optional[URIRef]:
        """
        Find the URI for a media type string.
        
        Args:
            media_type: e.g., "image/png"
            
        Returns:
            URIRef or None if not found
        """
        # First try direct W3C URI construction
        expected_uri = MediaTypeNamespaces.get_uri_for_media_type(media_type)
        if (expected_uri, RDF.type, OWL.Class) in self._graph:
            return expected_uri
        
        # Fallback: search by notation
        for s, _, _ in self._graph.triples((None, SKOS.notation, Literal(media_type))):
            if isinstance(s, URIRef):
                return s
        
        return None
    
    def print_summary(self) -> None:
        """Print summary of loaded data."""
        stats = self.get_stats()
        print("=" * 60)
        print("IANA Media Types Ontology (W3C Namespace)")
        print("=" * 60)
        print(f"Total triples:       {stats.total_triples:,}")
        print(f"Media types:         {stats.media_type_count:,}")
        print(f"Top-level types:     {stats.top_level_types}")
        print(f"Hierarchy edges:     {stats.subclass_edges:,}")
        print(f"Sources loaded:      {len(stats.sources)}")
        for src in stats.sources:
            print(f"  - {Path(src).name}")
        print("=" * 60)
        print()
        print("Namespace: https://www.w3.org/ns/iana/media-types/")
        print("Example:   https://www.w3.org/ns/iana/media-types/image/png#Resource")
        print("=" * 60)


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python loader.py <path-to-media-types.ttl>")
        print()
        print("First run: python download_iana.py data/iana-media-types/")
        print("Then run:  python loader.py data/iana-media-types/media-types.ttl")
        sys.exit(1)
    
    loader = MediaTypeLoader()
    loader.load(sys.argv[1])
    loader.print_summary()
    
    print("\nSample media types:")
    labels = loader.get_labels()
    for uri, label in sorted(labels.items(), key=lambda x: x[1])[:20]:
        print(f"  {label}")